### ISSUE TITLE
S3 Access Denied in Spark History Server

### ISSUE THREAD

**Issue by batCoder95** [bbenzikry/spark-eks#1]
Hi @bbenzikry, 

I am trying to setup the spark-history-server using the link you have provided and the values similar to what you have suggested in flux folder. I am using S3 bucket and IRSA (IAM Role) for accessing the bucket where event logs are stored. I already have a service-account setup, which is linked to an IAM role (IRSA) that has full access on the S3 bucket. Therefore, I am telling the helm chart not to create a new service-account, but instead use the existing one. Below is my helm command for reference:

`helm install spark-history-server --set rbac.create=false,serviceAccount.create=false,serviceAccount.name=svc-spark-iam,image.repository=bbenzikry/spark-eks,image.tag=spark3-latest,pvc.enablePVC=false,nfs.enableExampleNFS=false,service.type=ClusterIP,s3.enableS3=true,s3.logDirectory=s3a://spark-bucket/events/ stable/spark-history-server --namespace dev`

Now, once the pod is launched, I can see that the container is assuming the service-account defined above and is also assuming the IAM role associated with that service-account via RBAC. I can see the IAM role in the "AWS_ROLE_ARN" key on Pod environment when I describe the pod. But even then I am getting the Access Denied "403 Forbidden" Exception from S3, as below:

`Exception in thread "main" java.nio.file.AccessDeniedException: s3a://spark-bucket/events/: getFileStatus on s3a://spark-bucket/events/: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: 756F67F5ED6E44E1; S3 Extended Request ID: hdyxhz/KSXnB4HY5eWSlfikJzTbNPeo+w9BTysu9iL2QwQxZIc6Pb++aAzAH2NsldNDevsc1Fkg=; Proxy: null), S3 Extended Request ID: hdyxhz/KSXnB4HY5eWSlfikJzTbNPeo+w9BTysu9iL2QwQxZIc6Pb++aAzAH2NsldNDevsc1Fkg=:403 Forbidden`

Any idea why this would be happening? Would appreciate any guidance :)

**Comment by bbenzikry** [comment]
Hi @batCoder95, can you share the permissions you set for the bucket?

**Comment by batCoder95** [comment]
Hi @bbenzikry,

The IAM Role that is associated with the IRSA service account has the AWS Managed Policy "AmazonS3FullAccess" attached to it. I am attaching the screenshot of same for reference. This is the same role, service-account and bucket I am using in normal spark jobs running on same EKS and they are working perfectly fine.

Please let me know if I should share more details.
![IAM-Role-S3-Policy](https://user-images.githubusercontent.com/19374751/96369996-10c59a80-117a-11eb-836e-f03a63723353.PNG)

**Comment by batCoder95** [comment]
Hey @bbenzikry ,

It worked by including the SPARK_HISTORY_OPTS parameter in the helm installation command. Turns out we need to set the spark configuration `spark.hadoop.fs.s3a.aws.credentials.provider=com.amazonaws.auth.WebIdentityTokenCredentialsProvider` so that the IRSA permissions are used in the pod. Below is the final helm install command that I used to make it work:

`helm install spark-history-server --set rbac.create=false,serviceAccount.create=false,serviceAccount.name=svc-spark-iam,image.repository=bbenzikry/spark-eks,image.tag=spark3-latest,environment.SPARK_HISTORY_OPTS='-Dspark.hadoop.fs.s3a.aws.credentials.provider=com.amazonaws.auth.WebIdentityTokenCredentialsProvider',pvc.enablePVC=false,nfs.enableExampleNFS=false,service.type=ClusterIP,s3.enableS3=true,s3.logDirectory=s3a://spark-bucket/events/ stable/spark-history-server --namespace dev`

Closing this issue. Cheers :)

**Comment by bbenzikry** [comment]
Hmm, thanks for letting me know - in the forked chart we use it's specified as follows, it may have been changed.
```bash
if [ "$enableIAM" == "false" ]; then
              export SPARK_HISTORY_OPTS="$SPARK_HISTORY_OPTS \
              -Dspark.hadoop.fs.s3a.access.key=$(cat /etc/secrets/${accessKeyName}) \
              -Dspark.hadoop.fs.s3a.secret.key=$(cat /etc/secrets/${secretKeyName})";
            else
              export SPARK_HISTORY_OPTS="$SPARK_HISTORY_OPTS \
              -Dspark.hadoop.fs.s3a.aws.credentials.provider=com.amazonaws.auth.WebIdentityTokenCredentialsProvider";
            fi;
```

**Comment by ssilb4** [comment]
oh It saves my time. @batCoder95 thanks.
