### ISSUE TITLE
Support for Spark 3.1.1

### ISSUE THREAD

**Issue by ilikevenkat** [bbenzikry/spark-eks#4]
Hi,

I tried to follow the Dockerfile for Spark 3.1.1 but S3 connectivity in EKS didn't work. However same steps works for 3.0.1.

How can I find the right JARS combination? I get timeout error in 3.1.1:

> AmazonHttpClient: Unable to execute HTTP request: connect timed out
> java.net.SocketTimeoutException: connect timed out

**Comment by bbenzikry** [comment]
Hi, can you elaborate on that a bit? where did connectivity fail? 
Is the operator failing to access s3 or is the spark application failing during initialization? 

What spark build are you using? The docker files in this repo use my custom builds ( which are only up to date for 3.0.1 ) 

It would also help if you add your SparkApplication yaml

**Comment by ilikevenkat** [comment]
Hi bbenzikry,

I have deployed Spark Operator using Helm Chart. Then, followed your Dockerfile and created two images one for Spark 3.1.1 and one for Spark 3.0.1.

In spark application yaml configuration, I have Python code in MainApplication and inside the code I read csv from S3.

Spark 3.0.1 - > S3 = Works
Spark 3.1.1 - > S3 = Fails with timeout error.

My suspect is I need to use different version of Jar files for Spark 3.1.1. I am wondering how to identify the right jar version to be used? From where you were able to get Jar versions to be used for S3 connectivity for 3.0.1?

PS: Thanks for all your response in GoogleSparkOperator issues, it helped me a lot to establish connection in 3.0.1.

**Comment by bbenzikry** [comment]
Hi there @ilikevenkat, sorry for the late reply. 
AFAIK, AWS deps should work the same on 3.1.1 and 3.0.1
How are you authenticating to S3? 
It would really really help if you provide the yaml

**Comment by bbenzikry** [comment]
Closing as there was no reply + I'm going to release new documentation with Flux v2 and 3.1.2 examples soon.
