### ISSUE TITLE
several troubles

### ISSUE THREAD

**Issue by parisni** [bbenzikry/spark-eks#5]
hi, several feedbacks after testing this:

1. spark2 image actually contains spark3 on dockerhub
2. spark2 image does not connect to glue (empty default dataabse) on my tests
3. pyspark tags are not accessible on docker-hub
3. spark3 image breaks with datanucleus missing lib
4. released binary does not provide hadoop as stated here https://github.com/bbenzikry/spark-glue/releases

conclusion:

not being able to connect spark3 to glue

**Comment by bbenzikry** [comment]
Hi there,

* 1+3. I didn't notice images broke, could be something to do with the recent changes in Dockerhub, sorry for that. 
It's important to note that I'm actually planning to update the entire repo in a few days and revamp a large part of it 
( which has diverged a bit and focuses solely on spark 3, without hosting images )

2. As mentioned in the README
![image](https://user-images.githubusercontent.com/1993348/128762645-f58c05e9-d577-4fd5-a1c0-bd4a6f454525.png)

4. I've known many to use the spark3 images without running into an issue, did you try an older digest or just latest?

5. The release description doesn't do justice to the README which does say that it's w/o hadoop, but point taken. I've  deprecated the repo itself until I upload the new content to avoid any confusion.

If you're looking for the quickest way to spawn a full build to your liking - in the meantime I would suggest https://github.com/viaduct-ai/docker-spark-k8s-aws which nicely streamlines the different parts of what I do on the build side

**Comment by parisni** [comment]
thanks for the reply. in the meantime, I switched to this implementation https://github.com/kuhnen/spark-glue/tree/to_docker
and it worked.

**Comment by bbenzikry** [comment]
Great, I'll be closing this
